openapi: 3.0.4
info:
  title: API doc for RestaurantService
  version: 1.0.0
servers:
  - url: http://192.168.237.130:8000
    description: Local Ubuntu server

paths:
  /restaurant:
    post:
      summary: Create new restaurant
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                "name":
                  type: string
                "description":
                  type: string
                "address":
                  type: string
                "phone_number":
                  type: string
                "email":
                  type: string
                "status":
                  type: string
                  enum: [open, closed]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Restaurant"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Server Error
    get:
      summary: Get all restaurant details
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Restaurant"
        "400":
          description: Bad Request
        "404":
          description: Not found

  /restaurant/{restaurantID}:
    put:
      summary: Update Restaurant
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: restaurantID
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateRestaurantRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Restaurant"
        "400":
          description: Bad Request
        "404":
          description: Not found
        "401":
          description: Unauthorized
        "500":
          description: Server Error
    get:
      summary: get Restaurant by ID
      parameters:
        - in: path
          name: restaurantID
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:



components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Restaurant:
      type: object
      properties:
        id:
          type: integer
        manager_id:
          type: integer
        name:
          type: integer
        description:
          type: string
        address:
          type: string
        phone_number:
          type: string
        email:
          type: string
        status:
          type: string
          enum: [open, closed]
        menu_items:
          type: array
          items:
            $ref: "#/components/schemas/MenuItem"

    MenuItem:
      type: object
      properties:

    UpdateRestaurantRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        address:
          type: string
        phone_number:
          type: string
        email:
          type: string
        status:
          type: string
          enum: [open, closed]


